//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FractalFast0r.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FractalFast0r.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct VS_INPUT 
        ///{
        ///	float3 Position : POSITION0;
        ///	float2 Tex : TEXCOORD0;
        ///};
        ///
        ///struct PS_INPUT 
        ///{
        ///	float4 Position : POSITION0;
        ///	float2 Tex : TEXCOORD0;
        ///};
        ///
        ///PS_INPUT vs_main( VS_INPUT Input,
        ///        uniform float4x4 matViewProjection )
        ///{
        ///	PS_INPUT Output;
        ///
        ///	Output.Position = mul(matViewProjection, float4(Input.Position, 1));
        ///	Output.Tex = Input.Tex;
        ///
        ///	return Output;
        ///}
        ///
        ///
        ///
        ///float test : register(c7);
        ///
        ///float4 ps_main( PS_INPUT Input ) : COLOR0
        ///{
        ///	float2 c = Input.Tex;
        ///	float2 z = 0; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string shaders {
            get {
                return ResourceManager.GetString("shaders", resourceCulture);
            }
        }
    }
}
